
# ex) -Dspring.profiles.active=server|local

mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: mybatis/mapper/*.xml

spring:
    datasource:
        connectionProperties: characterEncoding=UTF-8
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#        driverClassName: org.postgresql.Driver
        type: org.apache.tomcat.jdbc.pool.DataSource
#        url: jdbc:postgresql://10.10.18.29:32768/postgres
        url: jdbc:log4jdbc:postgresql://10.10.18.29:32770/postgres
        password: postgres
        username: postgres
        initSQL: select 1
        tomcat:
          validation-query: SELECT 1
          test-on-borrow: true
          validation-interval: 0

    messages:
        basename: i18n/messages
        cache-seconds: -1
        encoding: UTF-8

    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    redis:
        host: 10.10.18.29
        port: 32771

    test:
        mockmvc:
            print: default

logging:
    level:
        mybatis:
            mapper: TRACE
        root: WARN
    ROOT: INFO
    com.koknantech.spring: DEBUG


---
spring:
    profiles: developer

